using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerCharacterMovement : MonoBehaviour
{

    [SerializeField]
    [Range(0,1000)] //This means that the MoveSpeed can be in range 0-1000
    private float MoveSpeed = 10.0f;

    // Start is called before the first frame update
    void Start()
    {

        Debug.Log("Hello World!");
        
    }

    // Update is called once per frame
    void Update()
    {
        float xInput = Input.GetAxis("Horizontal");
        float yInput = Input.GetAxis("Vertical");

        Vector3 oldPosition = transform.position;

        transform.position = oldPosition + new Vector3(xInput, yInput, 0) * MoveSpeed * Time.deltaTime;
    }
}
